export interface Quote {
  text: string
  author: string
}

/**
 * Curated, static collection — one is shown per day, picked
 * deterministically from the date so it stays stable all day and changes
 * tomorrow. No AI, no network: just timeless words.
 */
export const QUOTES: Quote[] = [
  { text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius' },
  { text: 'Waste no more time arguing about what a good man should be. Be one.', author: 'Marcus Aurelius' },
  { text: 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', author: 'Marcus Aurelius' },
  { text: 'The impediment to action advances action. What stands in the way becomes the way.', author: 'Marcus Aurelius' },
  { text: 'We suffer more often in imagination than in reality.', author: 'Seneca' },
  { text: 'Luck is what happens when preparation meets opportunity.', author: 'Seneca' },
  { text: 'It is not that we have a short time to live, but that we waste a lot of it.', author: 'Seneca' },
  { text: 'No man is free who is not master of himself.', author: 'Epictetus' },
  { text: 'First say to yourself what you would be; and then do what you have to do.', author: 'Epictetus' },
  { text: 'The journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
  { text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu' },
  { text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Confucius' },
  { text: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', author: 'Rumi' },
  { text: 'The wound is the place where the Light enters you.', author: 'Rumi' },
  { text: 'What you seek is seeking you.', author: 'Rumi' },
  { text: 'Raise your words, not your voice. It is rain that grows flowers, not thunder.', author: 'Rumi' },
  { text: 'Wherever you stand, be the soul of that place.', author: 'Rumi' },
  { text: 'Kal kare so aaj kar, aaj kare so ab — do today what you would do tomorrow, do now what you would do today.', author: 'Kabir' },
  { text: 'The river that flows in you also flows in me.', author: 'Kabir' },
  { text: 'Wherever you are is the entry point.', author: 'Kabir' },
  { text: 'You cannot cross the sea merely by standing and staring at the water.', author: 'Rabindranath Tagore' },
  { text: 'Faith is the bird that feels the light when the dawn is still dark.', author: 'Rabindranath Tagore' },
  { text: 'Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.', author: 'Rabindranath Tagore' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi' },
  { text: 'In a gentle way, you can shake the world.', author: 'Mahatma Gandhi' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Arise, awake, and stop not till the goal is reached.', author: 'Swami Vivekananda' },
  { text: 'Take up one idea. Make that one idea your life; dream of it; think of it; live on that idea.', author: 'Swami Vivekananda' },
  { text: 'All the powers in the universe are already ours. It is we who have put our hands before our eyes.', author: 'Swami Vivekananda' },
  { text: 'You cannot believe in God until you believe in yourself.', author: 'Swami Vivekananda' },
  { text: 'Dream is not that which you see while sleeping; it is something that does not let you sleep.', author: 'A. P. J. Abdul Kalam' },
  { text: 'If you want to shine like a sun, first burn like a sun.', author: 'A. P. J. Abdul Kalam' },
  { text: 'Excellence is a continuous process and not an accident.', author: 'A. P. J. Abdul Kalam' },
  { text: 'All of humanity’s problems stem from man’s inability to sit quietly in a room alone.', author: 'Blaise Pascal' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'Do not go where the path may lead; go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'The only way to make sense out of change is to plunge into it, move with it, and join the dance.', author: 'Alan Watts' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'It is never too late to be what you might have been.', author: 'George Eliot' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Will Durant' },
  { text: 'Knowing yourself is the beginning of all wisdom.', author: 'Aristotle' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
  { text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard' },
  { text: 'The best time to plant a tree was twenty years ago. The second best time is now.', author: 'Chinese proverb' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese proverb' },
  { text: 'A river cuts through rock not because of its power, but because of its persistence.', author: 'James N. Watkins' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln (attributed)' },
  { text: 'Whether you think you can, or you think you can’t — you’re right.', author: 'Henry Ford' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'Comparison is the thief of joy.', author: 'Theodore Roosevelt' },
  { text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau' },
  { text: 'It is not the mountain we conquer, but ourselves.', author: 'Edmund Hillary' },
  { text: 'Peace comes from within. Do not seek it without.', author: 'Buddhist teaching' },
  { text: 'Each morning we are born again. What we do today is what matters most.', author: 'Buddhist teaching' },
  { text: 'Drop by drop is the water pot filled.', author: 'The Dhammapada' },
  // From the user's collection — "100 Best Motivational Quotes", TheQuotes.Net
  { text: 'I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.', author: 'Maya Angelou' },
  { text: 'I don’t have time to hate people who hate me, because I’m too busy loving people who love me.', author: 'Unknown' },
  { text: 'Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.', author: 'Maya Angelou' },
  { text: 'Life is a tragedy when seen in close-up, but a comedy in long-shot.', author: 'Charlie Chaplin' },
  { text: 'Never blame anyone in life. Good people give happiness, bad people give experience, worst people give a lesson and best people give memories.', author: 'Unknown' },
  { text: 'We make a living by what we get; we make a life by what we give.', author: 'Winston Churchill' },
  { text: 'Never waste a minute thinking about people you don’t like.', author: 'Dwight Eisenhower' },
  { text: 'Put your heart, mind, and soul into even your smallest acts. This is the secret of success.', author: 'Swami Sivananda' },
  { text: 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', author: 'David Brinkley' },
  { text: 'Why hurry over beautiful things? Why not linger and enjoy them?', author: 'Clara Schumann' },
  { text: 'Look deep into nature, and then you will understand everything better.', author: 'Albert Einstein' },
  { text: 'Be faithful in small things because it is in them that your strength lies.', author: 'Mother Teresa' },
  { text: 'Doubt is a pain too lonely to know that faith is his twin brother.', author: 'Kahlil Gibran' },
  { text: 'Take the first step in faith. You don’t have to see the whole staircase, just take the first step.', author: 'Martin Luther King, Jr.' },
  { text: 'If you don’t like something, change it. If you can’t change it, change your attitude.', author: 'Maya Angelou' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'I count myself in nothing else as happy as in a soul remembering my good friends.', author: 'William Shakespeare' },
  { text: 'The past cannot be changed, forgotten, edited, or erased. It can only be accepted.', author: 'Unknown' },
  { text: 'It is not a lack of love, but a lack of friendship that makes unhappy marriages.', author: 'Friedrich Nietzsche' },
  { text: 'Better than a thousand hollow words, is one word that brings peace.', author: 'Buddha' },
  { text: 'The busy have no time for tears.', author: 'Lord Byron' },
  { text: 'We should not give up and we should not allow the problem to defeat us.', author: 'A. P. J. Abdul Kalam' },
  { text: 'All birds find shelter during a rain. But the eagle avoids rain by flying above the clouds. Problems are common, but attitude makes the difference!', author: 'A. P. J. Abdul Kalam' },
  { text: 'A clever person solves a problem. A wise person avoids it.', author: 'Albert Einstein' },
  { text: 'Friendship may, and often does, grow into love, but love never subsides into friendship.', author: 'Lord Byron' },
  { text: 'Whoever is careless with the truth in small matters cannot be trusted with important matters.', author: 'Albert Einstein' },
  { text: 'Money will buy you a pretty good dog, but it won’t buy the wag of his tail.', author: 'Henry Wheeler Shaw' },
  { text: 'A ship is always safe at the shore — but that is not what it is built for.', author: 'Albert Einstein' },
  { text: 'No one should be ashamed to admit they are wrong, which is but saying, in other words, that they are wiser today than they were yesterday.', author: 'Alexander Pope' },
  { text: 'Every man has his faults; I have and so have you — you will allow me to say so!', author: 'Clara Schumann' },
  { text: 'It’s important to focus on the solution, not the problem.', author: 'Donald Trump' },
  { text: 'Life’s too short to hang out with people who aren’t resourceful.', author: 'Jeff Bezos' },
  { text: 'Don’t find fault, find a remedy; anybody can complain.', author: 'Henry Ford' },
  { text: 'The safe way to double your money is to fold it over once and put it in your pocket.', author: 'Frank Hubbard' },
  { text: 'Vision without action is daydreaming and action without vision is a nightmare.', author: 'Chinese proverb' },
  { text: 'Never spend your money before you have earned it.', author: 'Thomas Jefferson' },
  { text: 'My best friend is the one who brings out the best in me.', author: 'Henry Ford' },
  { text: 'It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you’ll do things differently.', author: 'Warren Buffett' },
  { text: 'No matter how hard you hug your money, it never hugs back.', author: 'H. Jackson Brown, Jr.' },
  { text: 'Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1.', author: 'Warren Buffett' },
  { text: 'By all means marry; if you get a good wife, you’ll become happy; if you get a bad one, you’ll become a philosopher.', author: 'Socrates' },
  { text: 'Always laugh when you can. It is cheap medicine.', author: 'Lord Byron' },
  { text: 'For every minute you are angry you lose sixty seconds of happiness.', author: 'Ralph Waldo Emerson' },
  { text: 'The day the child realizes that all adults are imperfect, he becomes an adolescent; the day he forgives them, he becomes an adult; the day he forgives himself, he becomes wise.', author: 'Alden Nowlan' },
  { text: 'You are today the result of your thoughts of yesterday, and the many yesterdays preceding it. You are forming today the mold for what you will be in the years to come.', author: 'Robert Collier' },
  { text: 'You’ll miss the best things if you keep your eyes shut.', author: 'Dr. Seuss' },
  { text: 'The most important single ingredient in the formula of success is knowing how to get along with people.', author: 'Theodore Roosevelt' },
  { text: 'Worrying does not take away tomorrow’s troubles; it takes away today’s peace.', author: 'Unknown' },
  { text: 'All things in life are temporary. If going well, enjoy it — it will not last forever. If going wrong, don’t worry — it can’t last long either.', author: 'Unknown' },
  { text: 'Friendship is like a book. It takes a few seconds to burn, but it takes years to write.', author: 'Unknown' },
  { text: 'Many people will walk in and out of your life, but only true friends will leave footprints in your heart.', author: 'Eleanor Roosevelt' },
  { text: 'Don’t cry because it’s over. Smile because it happened.', author: 'Dr. Seuss' },
  { text: 'We are never defeated unless we give up on God.', author: 'Ronald Reagan' },
  { text: 'Say what you want but you never say it with violence!', author: 'Gerard Way' },
  { text: 'Don’t tell people how to do things, tell them what to do and let them surprise you with their results.', author: 'George S. Patton Jr.' },
  { text: 'When fate hands you a lemon, make lemonade.', author: 'Dale Carnegie' },
  { text: 'Do not pray for an easy life, pray for the strength to endure a difficult one.', author: 'Bruce Lee' },
  { text: 'Empty pockets never held anyone back. Only empty heads and empty hearts can do that.', author: 'Norman Vincent Peale' },
  { text: 'Try, try, try, and keep on trying is the rule that must be followed to become an expert in anything.', author: 'W. Clement Stone' },
  { text: 'Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.', author: 'Mark Twain' },
  { text: 'You only have to do a very few things right in your life so long as you don’t do too many things wrong.', author: 'Warren Buffett' },
  { text: 'A goal properly set is halfway reached.', author: 'Zig Ziglar' },
  { text: 'Never, never, never give up.', author: 'Winston Churchill' },
  { text: 'Life is really simple, but we insist on making it complicated.', author: 'Confucius' },
  { text: 'One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.', author: 'Thomas Alva Edison' },
  { text: 'Arguments are to be avoided: they are always vulgar and often convincing.', author: 'Oscar Wilde' },
  { text: 'Yes we can!', author: 'Barack Obama' },
  { text: 'You can’t let your failures define you. You have to let your failures teach you.', author: 'Barack Obama' },
  { text: 'A pretty face may be enough to catch a man, but it takes character and good nature to hold him.', author: 'Thomas More' },
  { text: 'Love yourself. Love the world. There is no power stronger than love.', author: 'Deepak Chopra' },
  { text: 'The good life is one inspired by love and guided by knowledge.', author: 'Bertrand Russell' },
  { text: 'I’m not afraid of anything. That’s just the way I am.', author: 'Paul Walker' },
  { text: 'The best protection for the people is not necessarily to believe everything people tell them.', author: 'Demosthenes' },
  { text: 'Who controls the past controls the future. Who controls the present controls the past.', author: 'George Orwell' },
  { text: 'Make sure you are doing what God wants you to do — then do it with all your strength.', author: 'George Washington' },
  { text: 'Never underestimate the pain of a person, because in all honesty, everyone is struggling. Some people are just better at hiding it than others.', author: 'Will Smith' },
  { text: 'Facts are many, but the truth is one.', author: 'Rabindranath Tagore' },
  { text: 'Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.', author: 'Epicurus' },
  { text: 'It is better to destroy one’s own errors than those of others.', author: 'Democritus' },
  { text: 'The less you open your heart to others, the more your heart suffers.', author: 'Deepak Chopra' },
  { text: 'A successful marriage requires falling in love many times, always with the same person.', author: 'Mignon McLaughlin' },
  { text: 'Happy is the man who finds a true friend, and far happier is he who finds that true friend in his wife.', author: 'Franz Schubert' },
  { text: 'Never think hard about the past, it brings tears. Don’t think more about the future, it brings fears. Live this moment with a smile, it brings cheers.', author: 'Unknown' },
  { text: 'Do you know why God created gaps between fingers? So that someone who is special to you comes and fills those gaps by holding your hand forever.', author: 'Unknown' },
  { text: 'We must be willing to let go of the life we have planned, so as to have the life that is waiting for us.', author: 'E. M. Forster' },
  { text: 'A mirror reflects a man’s face, but what he is really like is shown by the kind of friends he chooses.', author: 'Colin Powell' },
  { text: 'We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.', author: 'Maya Angelou' },
  { text: 'You can’t be scared to die for the truth. The truth is the only thing that is ever going to be constant.', author: 'Will Smith' },
  { text: 'Never discourage anyone who continually makes progress, no matter how slow.', author: 'Plato' },
  { text: 'A healthy relationship doesn’t drag you down; it inspires you to be better.', author: 'Mandy Hale' },
  { text: 'Let no man pull you low enough to hate him.', author: 'Martin Luther King, Jr.' },
  { text: 'You can never cross the ocean until you have the courage to lose sight of the shore.', author: 'Christopher Columbus' },
  { text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain' },
  { text: 'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.', author: 'Erma Bombeck' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'If you want to lift yourself up, lift up someone else.', author: 'Booker T. Washington' },
  { text: 'It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.', author: 'Ann Landers' },
  { text: 'If you accept such love with purity and humility, you will understand that love is neither giving nor receiving — it is participating.', author: 'Paulo Coelho' },
  { text: 'Never again help anyone to feel as though they have a right to feel badly.', author: 'Guy Finley' },
]

function hashKey(key: string): number {
  let h = 0
  for (let i = 0; i < key.length; i++) {
    h = (h * 31 + key.charCodeAt(i)) >>> 0
  }
  return h
}

/** The day's quote — same all day, different tomorrow. */
export function quoteForDate(dateKey: string): Quote {
  return QUOTES[hashKey(dateKey) % QUOTES.length]
}

/** A different quote from the day's one, for the shuffle button. */
export function anotherQuote(current: Quote): Quote {
  if (QUOTES.length < 2) return current
  let next = current
  let guard = 0
  while (next.text === current.text && guard < 10) {
    next = QUOTES[Math.floor(Math.random() * QUOTES.length)]
    guard++
  }
  return next
}
